export { default as Alert } from './Alert'
export { default as NavBar } from './NavBar'
export { default as Calculadora } from './Calculadora'
export { default as ResultadoCalculadora } from './ResultadoCalculadora'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as CardContributors } from './CardContributors'
